### ISSUE TITLE
Bij het uploaden van een plattegrond wordt de plattegrond onder de placeholder weergegeven. 

### ISSUE THREAD

**Issue by Raymond-Wijkhuizen** [TselmegGantuya/AirLab#3]
Selecteer een bestand voor het uploaden van een plattegrond.
Een correcte foto zal half onder het display weergegeven worden.
Na refreshen van de pagina staat de foto op de correcte locatie.

**Comment by TselmegGantuya** [comment]
Dit is om te laten zien wat je heb geupload en de correcte locatie voor de nieuwe plattegrond.
