### ISSUE TITLE
Bij het maken van een aanpassing in de naam van een plattegrond wordt ‘file’ niet veranderd maar blijft als een eigen afbeelding.

### ISSUE THREAD

**Issue by Raymond-Wijkhuizen** [TselmegGantuya/AirLab#8]
Het maakt niet uit hoe vaak je de naam van een plattegrond veranderd. Er zal altijd een 'file' blijven staan

**Comment by TselmegGantuya** [comment]
Deze bug is aangepast in de nieuwe release Airlab(Alpha).
